[package]
name = "iridium-rust-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iridium-client = "0.1.0"
tokio = "1.32.0"
warp = "0.3.6"
